# Generated by Django 5.2.4 on 2025-07-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_studymaterial_likes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studymaterial',
            name='shop_studym_is_publ_75367b_idx',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='is_public',
        ),
    ]
