# Generated by Django 5.2.4 on 2025-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_studymaterial_shop_studym_is_publ_75367b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialview',
            index=models.Index(fields=['ip_address'], name='shop_materi_ip_addr_6c0c00_idx'),
        ),
    ]
