# Generated by Django 5.2.4 on 2025-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_materialview_shop_materi_ip_addr_6c0c00_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted')], default='posted', max_length=20),
        ),
    ]
