# Generated by Django 5.2.4 on 2025-08-02 07:58

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('join', 'Join Our Team'), ('problem', 'Report a Problem'), ('help', 'Get Help/Talk')], default='join', max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(blank=True, help_text='PDF or DOCX files only (max 5MB)', null=True, upload_to=shop.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('issue_type', models.CharField(blank=True, choices=[('technical', 'Technical Problem'), ('account', 'Account Issue'), ('payment', 'Payment Problem'), ('other', 'Other')], max_length=10, null=True)),
                ('screenshot', models.ImageField(blank=True, help_text='Max 2MB (PNG, JPG, GIF)', null=True, upload_to=shop.models.get_upload_path)),
                ('help_topic', models.CharField(blank=True, choices=[('getting-started', 'Getting Started'), ('account', 'Account Settings'), ('payments', 'Payments'), ('talk', 'Talk'), ('other', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Join Application',
                'verbose_name_plural': 'Join Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
