# Generated by Django 5.2.4 on 2025-08-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_joinapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinApplication',
        ),
    ]
