# Generated by Django 5.2.4 on 2025-08-02 08:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_joinapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('join', 'Join Our Team'), ('problem', 'Report a Problem'), ('help', 'Get Help/Talk')], default='join', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.FileField(blank=True, help_text='Upload PDF or DOCX file (max 5MB)', null=True, upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('issue_type', models.CharField(blank=True, choices=[('technical', 'Technical Problem'), ('account', 'Account Issue'), ('payment', 'Payment Problem'), ('other', 'Other')], max_length=20, null=True)),
                ('screenshot', models.ImageField(blank=True, help_text='Upload screenshot (max 2MB)', null=True, upload_to='problem_screenshots/%Y/%m/')),
                ('help_topic', models.CharField(blank=True, choices=[('getting-started', 'Getting Started'), ('account', 'Account Settings'), ('payments', 'Payments'), ('talk', 'Talk'), ('other', 'Other')], max_length=20, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Join Application',
                'verbose_name_plural': 'Join Applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['purpose'], name='shop_joinap_purpose_a3e56e_idx'), models.Index(fields=['status'], name='shop_joinap_status_ada839_idx'), models.Index(fields=['submitted_at'], name='shop_joinap_submitt_80be7d_idx'), models.Index(fields=['email'], name='shop_joinap_email_bf25b8_idx')],
            },
        ),
    ]
