# Generated by Django 5.2.4 on 2025-08-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_joinapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Check this box to approve the material for public viewing', verbose_name='Approved'),
        ),
    ]
