# Generated by Django 5.2.4 on 2025-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_studymaterial_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Check this box to approve the task for public viewing', verbose_name='Approved'),
        ),
    ]
